[package]
name = "SendAsset"
version = "2.0.0"
authors = []
edition = "2.0"

[addresses]
sendasset_system= "0xfcd381dce435315523c7a0940729b3ff40ef9d5b0f206f214e8685f8bca2ca9c"

[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]


